### ISSUE TITLE
Crash on 3.0.0-rc2: Fatal Exception: java.lang.NullPointerException Attempt to read from field 'android.util.SparseArray i.c.a.n.a.m' on a null object reference

### ISSUE THREAD

**Issue by ctarabusi** [bluelinelabs/Conductor#626] opened 2020-10-14 14:08 UTC
We had a crash in the Conductor library 3.0.0-rc2

It happened on a Sony Xperia XZ2 with Android 10

Here is the complete stacktrace:

```
Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'android.util.SparseArray i.c.a.n.a.m' on a null object reference
com.bluelinelabs.conductor.internal.LifecycleHandler.unregisterForActivityResults (LifecycleHandler.java:1)
com.bluelinelabs.conductor.ActivityHostedRouter.unregisterForActivityResults (ActivityHostedRouter.java:1)
com.bluelinelabs.conductor.Controller.destroy (Controller.java:9)
com.bluelinelabs.conductor.Controller.destroy (Controller.java:1)
com.bluelinelabs.conductor.Backstack.pop (Backstack.java:1)
com.bluelinelabs.conductor.Router.B (Router.java:19)
de.teufel.android.app.bluetooth.external.ui.MainActivity.pushBackController (MainActivity.java:11)
```

Do you have any recommendations? Is it maybe fixed in some recent 3.0.0-rcX versions?

Thanks in advance,
Christian

**Comment by EricKuck** [comment] 2020-11-03 22:19
It's hard to tell with the obfuscated stacktrace, but I think this is a duplicate of #567, which was fixed with #629

**Closed as completed by EricKuck** 2020-11-03 22:19 UTC
