### ISSUE TITLE
Lifecycle diagram has attach/detach and save/restore not being symmetric around focus.

### ISSUE THREAD

**Issue by JakeWharton** [bluelinelabs/Conductor#6] opened 2016-04-01 04:37 UTC
Is this by design or an error in the docs? Can you explain why if the former?

**Comment by EricKuck** [comment] 2016-04-01 04:55
Now that you point it out, this does look strange in the digram. It is by design, however. 

`onRestoreViewState` is called before `onAttach` in order to ensure that the view is properly restored before it's actually visible to the user.

`onSaveViewState` is called before `onDetach` in order to make sure that the view state being saved wasn't in any way altered by being detached from the window.

In the most common case (the developer opting to allow their view to be dereferenced when the controller is pushed onto the backstack and another controller replaces it), the view will then be unbound and eventually garbage collected. When the controller is brought back to the foreground, its view will be re-inflated, re-bound, and its state will be restored.

In the less common case of the developer opting to have Conductor retain their views, even when not on screen (useful for complex view hierarchies), the view's state will never need to be restored, so this step will be skipped, which creates an asymmetric path in the lifecycle diagram.

Sorry, that got kind of wordy. Hopefully it answered your question though. Let me know if I wasn't clear on something.

**Comment by JakeWharton** [comment] 2016-04-01 05:20
> `onRestoreViewState` is called before `onAttach` in order to ensure that the view is properly restored before it's actually visible to the user.

Did you experience something that led to this decision? I'm not saying it's wrong, just that in our internal library which does our view orchestration we invert these two so they're symmetric and haven't seen any problems. They're called in the same frame one after the other for us (and before the view's natural measure/layout) so it still happens before going on screen.

> In the less common case of the developer opting to have Conductor retain their views, even when not on screen (useful for complex view hierarchies), the view's state will never need to be restored, so this step will be skipped, which creates an asymmetric path in the lifecycle diagram.

Ok interesting. That almost makes me want to see them on the outside of attach/detach such that you can skip _both_ save and restore (i.e., #9). In the current case you still pay the cost of save even though you will never restore since the view is never torn down.

**Comment by EricKuck** [comment] 2016-04-01 21:24
After looking through all the code again, there are a few other reasons for the asymmetrical design that I glossed over in my initial response.

`onRestoreViewState` is called before `onAttach` because `onAttach` can be called multiple times after view creation (in the case that the developer opts to retain the view, it will be reattached every time the controller comes back to the foreground). If `onRestoreViewState` came after `onAttach`, it would have to become a conditional call based on whether or not the view's state had already been restored, which makes the lifecycle a bit more awkward.

`onSaveViewState` is called before `onDetach` because of constraints caused by the host Activity's lifecycle. Since the Activity's `onSaveInstanceState` is called before it actually detaches its views from the window, the view's state will need to be saved before detach. The only way I could think of to get around this is to call `onDetach` whenever `onSaveInstanceState` is called, since this call will always mean the view will be detached soon. Making this change would also make #10 possible, but it feels wrong to call `onDetach` when the view isn't actually detached. Thoughts?

**Comment by EricKuck** [comment] 2016-04-04 15:28
Quick update: The changes needed to make this call symmetrical have been made and will be pushed in the next update. Save/restore will now outside of attach/detach.

**Comment by JakeWharton** [comment] 2016-04-04 15:40
Looking forward to seeing it!

**Comment by EricKuck** [comment] 2016-04-04 22:25
This is now fixed in 1.1.0. Thanks again for the input.

**Closed by EricKuck** 2016-04-04 22:25 UTC
