### ISSUE TITLE
RouterPagerAdapter with ChangeHandler that does not remove view

### ISSUE THREAD

**Issue by cody1024d** [bluelinelabs/Conductor#221] opened 2017-02-06 20:30 UTC
I don't mean to spam issues, but I want to address my previous issue (#220) now that I've reproduced it, and found more information about it.

The issue stems from a custom change handler, that allows me to fade in a dialog-esque view.

```java
public class FadeInChangeHandler extends AnimatorChangeHandler {

    public FadeInChangeHandler() {
        super(false);
    }

    @NonNull
    @Override
    protected Animator getAnimator(@NonNull ViewGroup container, @Nullable View from, @Nullable View to, boolean isPush, boolean toAddedToContainer) {
        AnimatorSet animator = new AnimatorSet();
        if (to != null && toAddedToContainer) {
            ObjectAnimator anim = ObjectAnimator.ofFloat(to, View.ALPHA, 0, 1);
            anim.setDuration(250);
            animator.play(anim);
        }

        return animator;
    }

    @Override
    protected void resetFromView(@NonNull View from) {

    }
}
```

As you can see, I am forcing the previous view to NOT be removed from the container, so that I can have a dialog like view displayed to the user.

When this change handler is used to display a dialog, and THEN the user navigates to a different page in such a way that it causes the previous page to be destroyed (such as page 0 to page 2), the view stack seems to go wonky.

I have re-created the issue in a fork of the demo project found here: [https://github.com/maoueh/Conductor/tree/bug/navigation-inside-view-pager-not-working](url)

Steps to reproduce the view-stack I'm seeing:

1. Open View Pager demo section
2. On first page, hit the Dialog-Next button (top one).  This should display a text box in the middle of the screen with a gray-transparent background around the previous controller.
3. Navigate to Page 2 using the view pager.
4. Navigate back to Page 0 (where the dialog controller is displayed)
5. Press on the textbox (or back button) to dismiss the top most controller (the dialog controller).
6. Press the Clear-Next button (bottom one).  This should display a text box with a clear background.

Following the above steps, you will see the original page displayed beneath the controller with the clear background.  However, if you were to NOT switch pages, and instead just open and close the dialog-controller, and then open the second controller, the clear-background would show as white (the window background).

All of the above leads me to believe that the RouterPagerAdapter is incorrectly saving view-state when previous views are not removed from the stack, although I could be wrong on that point.

@maoueh

**Comment by EricKuck** [comment] 2017-02-06 23:22
The link you posted to your code is on another user's fork. I looked for your fork, but it didn't have any code. I'm not sure where to look for your example?

**Comment by cody1024d** [comment] 2017-02-07 00:08
Hey Eric,

I did fork the project from another user, @maoueh's fork, as he was helping me in the other issue, and began trying to reproduce it.  It's VERY possible I forgot to push up the local changes though, and will confirm tomorrow.

I will also override that method, as that also seems very likely based on what I was seeing in the debugger.

Thanks again.

**Comment by maoueh** [comment] 2017-02-07 04:57
@EricKuck Changes here: https://github.com/maoueh/Conductor/compare/bug/navigation-inside-view-pager-not-working...cody1024d:bug/navigation-inside-view-pager-not-working (commit https://github.com/cody1024d/Conductor/commit/3c349a5c001ecd69350ca167f436f874309b1216).

```
git remote add cody1024d https://github.com/cody1024d/Conductor.git
git fetch cody1024d
git checkout bug/navigation-inside-view-pager-not-working
```

There seems to be a small compilation error: `.pushChangeHandler(new FadeInChangeHandler(false))` (in `ChildController.java`) but `FadeInChangeHandler` doesn't take any arguments. Just removing `false` parameter fix the compilation problem.

I don't quite get step 4. I think there is missing a "instruction". Here what I think step 4 should be. But before all, a step 0 is needed I think to make think more obvious:
 * In page 0, press `CLEAR NEXT!` button to see "expected" behavior and press back button right after.

Then, step 4 should read as:
 * Go back to Page 0 (without having done anything in Page 2), press the back button, the press the `CLEAR NEXT!` button. The controller is shown inside old Dialog "container". So, just to recap, here steps as I see them:

 1. Open View Pager demo app.
 2. In page 0, press `CLEAR NEXT!` button.
 3. Press back button pop change.
 4. Then press on `DIALOG NEXT!` button.
 5. With the "dialog" open, change to page 2.
 6. Without having done anything in page 2, go back to page 0.
 7. Press back button to dismiss "dialog"
 8. Press `CLEAR NEXT!` button, the controller is then showed inside previous controller container (it's not taking full height anymore).

I did not check why this happen, but I can reproduce your problem at least :)

**Comment by cody1024d** [comment] 2017-02-07 13:15
@maoueh  Thank you for helping me clarify! :)

**Comment by EricKuck** [comment] 2017-02-07 16:23
Thanks for the demo app. That was super helpful. This should now be fixed in the latest snapshot.

**Closed** 2017-02-07 16:22 UTC

**Comment by cody1024d** [comment] 2017-02-07 16:53
No problem! --I'm using this library in production in several places, so helping you guys, is helping myself too lol
