### ISSUE TITLE
Why is edit text reopening keyboard automatically on attach?

### ISSUE THREAD

**Issue by ursusursus** [bluelinelabs/Conductor#538] opened 2019-05-09 06:02 UTC
Hi, I have. a controller with a edit text, automatically or manually I open keyboard for that edit text, Now I press home button, move to another app.

 Now I come back to my app, edit text get focused (probably ok) but keyboard gets opened auyomatically.

The desired behaviour as per multi activity arch would be that keyboard should not show up again automatically. None of the apps do this.

Also, it shows up even when dismissed by back button, then moved away and moved back

Any idea why do this and how to fix this?

Thanks

**Comment by manueldidonna** [comment] 2019-05-09 06:23
Try with windowSoftInputMode, it's a manifest attribute.
Go [here](http://developer.android.com/guide/topics/manifest/activity-element.html#wsoft) for a description of the accepted values

**Comment by ursusursus** [comment] 2019-05-09 06:25
Sorry I dont want that. The issue is keyboard coming back after resuming paused app

**Comment by manueldidonna** [comment] 2019-05-09 08:08
Have you tried with "stateHidden"? It works for me

**Comment by Zhuinden** [comment] 2019-07-21 19:30
Have you tried android:descendantFocusability="blocksDescendants"  ?

**Comment by EricKuck** [comment] 2019-08-13 16:14
Closing as this isn't a Conductor issue, but is caused by the way Views and focusability work. The solutions posted here should work.

**Closed as completed by EricKuck** 2019-08-13 16:14 UTC
