### ISSUE TITLE
OnAttach incorrectly called again when using AutoTransitionChangeHandler()

### ISSUE THREAD

**Issue by ZakTaccardi** [bluelinelabs/Conductor#113] opened 2016-09-11 23:38 UTC
No problems here.

```

router.pushController(
                    RouterTransaction.with(childController)
                            .pushChangeHandler(FadeChangeHandler())   //  <--
                            .popChangeHandler(FadeChangeHandler())
```

Problem occurs here

```
router.pushController(
                    RouterTransaction.with(childController)
                            .pushChangeHandler(AutoTransitionChangeHandler())  //  <--
                            .popChangeHandler(FadeChangeHandler())
```

Let's say I have `parentController` and `childController`.  I am doing a transaction from `parentController` -> `childController`, and the following bug occurs when the `childController` is in the foreground (and `parentController` is in the background)

When using the `AutoTransitionChangeHandler`, `onAttach()` is called for `childController` and _then_ `onAttach()` is called for the parent, even though the parent should be in the detached state. It looks like `AutoTransitionChangeHandler` is temporarily re-attaching and re-detaching the `parentController`.

No problems when using the `FadeChangeHandler`.

**Comment by sockeqwe** [comment] 2016-09-12 08:09
This is because autotransition may or may not detach / attach the view that
should be animated during (at the start or at the end) the autotransition
animation ... Check your animations and if the boolean flag detach of
AutoTransitionChangeHandler() constructor is set properly ...

Zak Taccardi <notifications@github.com> schrieb am Mo., 12. Sep. 2016,
01:38:

**Comment by EricKuck** [comment] 2016-09-12 15:38
Exactly as @sockeqwe said, Android is actually detaching/attaching/detaching your view in very quick succession in order to calculate the diff of all of the shared elements. I've tried to figure out a way to suppress the `onAttach` and `onDetach` calls caused by transitions, but haven't had any luck. If anyone knows something I don't, please share!

FWIW, it seems like this is now fixed in Nougat.

**Comment by ZakTaccardi** [comment] 2016-09-12 15:45
oh man good thing I was on marshmallow or I might have missed this. 

Hopefully you/someone finds a brilliant way to fix this :)

**Comment by EricKuck** [comment] 2016-09-12 15:52
I just re-read your initial post...are you saying that `onAttach` is called and `onDetach` is not immediately called afterwards? From everything I've seen they're called within a millisecond or two of each other by the system. If `onDetach` isn't being called, that's something we should definitely fix.

**Comment by ZakTaccardi** [comment] 2016-09-12 16:28
in `onAttach` of both my parent and child controllers, (think master/detail, but for single-pane portrait mode), I am setting the Toolbar title to either `Parent` or `Child`, based on the current active controller

what happens is that the Toolbar is set to `Child` (when `childController`'s `onAttach` is called), and then the title is set to `Parent` (when the `parentController` has its `onAttach`/`onDetach`  quickly called during the `AutoTransition`.

So the toolbar's title ends up being `Parent` when the ChildController is active`. This only happens because of the quick attach/detach of the parent controller during the auto-transition

**Comment by EricKuck** [comment] 2016-10-06 21:00
I know I've seen this happen in the past, but am having a terrible time reproducing it now for some reason. Tried on a Nexus 5 (API 23), Nexus 6P (API 24), and a ton of emulators and I'm not seeing the multiple `onAttach` calls. Anyone know what's up or how I can easily reproduce?

**Comment by EricKuck** [comment] 2016-11-02 17:05
Finally reproduced it on another project. Should be working correctly now!

**Closed** 2016-11-02 17:04 UTC

**Comment by ZakTaccardi** [comment] 2016-11-02 17:09
Amazing, thank you! Hopefully it plays nice across recent Android versions!

**Comment by leonardo2204** [comment] 2016-11-03 01:13
Is this somehow related to my #87 issue ?
