### ISSUE TITLE
Broken on Android 12

### ISSUE THREAD

**Issue by ursusursus** [bluelinelabs/Conductor#661] opened 2021-12-27 15:13 UTC
Hi,
when running on Android 12 (Pixel 5), after backpress activity is only paused/stopped, not destroyed. 
After resuming/starting, library is in a weird invalid state, `parentController` is null when is shouldn't be etc, causing crashes.

This doesn't happen, if the activity is paused/stopped via home button, and then resumed.

Possibly related to https://github.com/bluelinelabs/Conductor/issues/659

@PaulWoitaschek @EricKuck

**Comment by ursusursus** [comment] 2022-01-10 11:47
Any pointer where should I look to attempt a pr?

**Comment by DavidBertet** [comment] 2022-01-21 04:45
I was facing the same issue, unfortunately I'm not sure how it can be fixed in Conductor itself. The router is used recursively, and popping the last controller is required in most cases.

Let's explain

My activity was calling `router.handleBack()` in `onBackPressed` as in the [example](https://github.com/bluelinelabs/Conductor#minimal-activity-implementation)

The issue is, when the user taps the back button on the root controller with Android 12
- it calls `onBackPressed`, which is going to [pop the controller](https://github.com/bluelinelabs/Conductor/blob/03701d05a9362d96fa80c20173342b8a311c71d3/conductor/src/main/java/com/bluelinelabs/conductor/Router.java#L97)
- the app is no longer destroyed, but stoped

=> When the user comes back, the controller has already been destroyed, nothing is going to recreate it.
That doesn't happen with the home button as `onBackPressed ` isn't called, so the controller doesn't pop.

To avoid popping the root controller, we can update the code of the activity as is
```
override fun onBackPressed() {
    if (router.backstackSize <= 1 || !router.handleBack()) {
        super.onBackPressed()
    }
}
```

PS: My case is slightly more different as I used a `childRouters` for each tabs. I check for the `backstackSize` of the `childRouter` currently visible, but the idea is basically the same - never pop the head as it won't come back!

**Closed as completed** 2022-01-27 22:41 UTC

**Comment by EricKuck** [comment] 2022-01-27 22:45
Version `3.1.3` of the app has a fix for this. Unfortunately this type of issue is impossible to fix automatically in the library, but it exposes a new `Router.setPopRootControllerMode` method that allows you to control what happens when it comes time to pop the final controller of a router. Options are:

- `NEVER`: Do nothing, don't pop at all. This is what you want for all Activities, and for all child controllers that you don't want to pop.
- `POP_ROOT_CONTROLLER_BUT_NOT_VIEW`: This has been the default behavior of the library since day 1.
- `POP_ROOT_CONTROLLER_AND_VIEW`: This is equivalent to the old `setPopsLastView(true)` method.

**Comment by ursusursus** [comment] 2022-01-27 22:49
Could you please show to use this, to solve this issue? `If os >= Android12 then NEVER else POP_ROOT_CONTROLLER_BUT_NOT_VIEW ` ?

**Comment by EricKuck** [comment] 2022-01-27 22:50
What's the harm in always using `NEVER`?

**Comment by ursusursus** [comment] 2022-01-27 22:52
I'm not sure, I'm just trying to replicate Android 11 behavior on the 12.

So, if it is `NEVER` then on 12 it doesnt pop it, so that fixes the issue, and below 12 it doesn't matter, since the activity is getting destroyed anyways, right?

**Comment by EricKuck** [comment] 2022-01-27 22:59
Yes that's correct. I will personally be using `NEVER` in Activities regardless of OS version. If you do decide you want to prevent this change from affecting Android 11 and below for whatever reason you could always use something like `router.setPopRootControllerMode(if (Build.VERSION.SDK_INT >= 31) PopRootControllerMode.NEVER else PopRootControllerMode.POP_ROOT_CONTROLLER_BUT_NOT_VIEW)`

**Comment by ursusursus** [comment] 2022-01-27 23:01
Right, I wonder if this should be the default behavior of Router

**Comment by EricKuck** [comment] 2022-01-27 23:02
It may be in the future, but this would break some of today's use cases. If it becomes the default behavior, it would happen in a major version bump.
