### ISSUE TITLE
Router#setRoot() method removes only one child view of container layout?

### ISSUE THREAD

**Issue by amylovesong** [bluelinelabs/Conductor#336] opened 2017-07-31 08:10 UTC
In Router class, setRoot() method will invoke removeAllExceptVisibleAndUnowned() method to remove child views of container：

```
private void removeAllExceptVisibleAndUnowned() {
    List<View> views = new ArrayList<>();

    ......

    final int childCount = container.getChildCount();
    for (int i = 0; i < childCount; i++) {
        final View child = container.getChildAt(i);
        if (!views.contains(child)) {
            container.removeView(child);
        }
    }
}
```

When I debug my project, views is empty and there are two children in the container, after removeView(), the first child is removed and the second child becomes the first one, so it's not been removed, is this right?

**Comment by EricKuck** [comment] 2017-08-01 21:00
I'm not really following exactly what you're seeing. Could you maybe send a quick demo or way I can reproduce this?

**Comment by EricKuck** [comment] 2017-08-01 21:02
Ah it looks like after removing a view the indices will be screwed up, meaning the view directly after the one that was just removed will stick around. Is this what you meant? If so, it's fixed now and thanks for letting me know! If not, please feel free to reopen.

**Closed as completed** 2017-08-01 21:13 UTC

**Comment by amylovesong** [comment] 2017-08-03 05:47
Yes, that's what I mean~ 👍
