### ISSUE TITLE
on fast rotation (portrait/lansdcape),  viewController crash

### ISSUE THREAD

**Issue by svakulenko** [bluelinelabs/Conductor#33] opened 2016-04-26 15:40 UTC
Hi
I start to using this lbrary, looking nice.
Now I have dashboard view with view pager which include recyclerView. 
On rotation, i got crash (not always but very frequently ) in base Controller.java class.

Any ideas ?
Thanks!

04-26 17:34:41.439 28412-28412/com.app.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.app.app, PID: 28412
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
                                                                         at com.bluelinelabs.conductor.Controller.attachChildController(Controller.java:689)
                                                                         at com.bluelinelabs.conductor.Controller.attach(Controller.java:760)
                                                                         at com.bluelinelabs.conductor.Controller.access$400(Controller.java:38)
                                                                         at com.bluelinelabs.conductor.Controller$6.onViewAttachedToWindow(Controller.java:848)
                                                                         at android.view.View.dispatchAttachedToWindow(View.java:15816)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3137)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3145)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3145)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3145)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3145)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3145)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3145)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1731)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:158)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by EricKuck** [comment] 2016-04-26 19:41
Any chance you could put a little demo app together for this? I couldn't reproduce it after a little testing, but you might be doing something different than me.

**Comment by martiall** [comment] 2016-04-27 11:56
Hi!

I'm from the same team than @svakulenko. I reproduced the issue and found out that during the rotation process mView is destroyed and created twice. As a result, it's attached and detached twice and onViewAttachedToWindow is called twice.

Sometimes (race condition ?), onViewAttachedToWindow is called in the interval when mView is null which caused the crash in attachChildController.

I fixed the issue by removing the OnAttachStateChangeListener in removeViewReference before setting mView at null. Not sure about the side effects of this fix.

What do you think about this ?

Diff attached :
[Fix-crash-when-rotating-a-ViewPager-based-Controller.txt](https://github.com/bluelinelabs/Conductor/files/238554/Fix-crash-when-rotating-a-ViewPager-based-Controller.txt)

**Comment by sockeqwe** [comment] 2016-04-27 11:59
Do you use TransitionManager (Api 19+)?

**Comment by svakulenko** [comment] 2016-04-27 12:13
Hi
No.
Child controller are added like in "demo" app : 

   ChildControllerTransaction transaction = ChildControllerTransaction.builder( new SettingController().setRoomName(item.getName()), R.id.overlay_slot)
                .pushChangeHandler(new FadeChangeHandler(200))
                .popChangeHandler(new FadeChangeHandler(200))
                .addToLocalBackstack(true)
                .build();


By the way, there are no participation of child controllers in test.

**Comment by EricKuck** [comment] 2016-04-27 20:15
I still wasn't able to reproduce, but removing the OnAttachStateChangeListener before removing the view reference is something we probably should have been doing anyway, so I made the change you proposed in f8a05731d9d6b678b62f213b56af953f7cc879b9. I'm closing the issue assuming that'll fix it for you. If it doesn't, feel free to reopen.

**Closed by EricKuck** 2016-04-27 20:15 UTC

**Comment by martiall** [comment] 2016-04-28 07:50
We will keep you updated about this if the fix doesn't do the job :)

Thank you for the quick feedbacks.
