### ISSUE TITLE
Permit push when there is no root controller?

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#245] opened 2017-03-09 08:40 UTC
I received a stackoverflow error where `getTransactionIndexer` was called in an infinite loop. I'm not 100% sure but this is what I assume:

I called `push` on a router that had no root controller. Therefore this chain was called:

`Router#pushController`
-> 
`Router#performControllerChange(@Nullable RouterTransaction to, @Nullable RouterTransaction from, boolean isPush)`
 -> 
`Router#performControllerChange(@Nullable final RouterTransaction to, @Nullable final RouterTransaction from, boolean isPush, @Nullable ControllerChangeHandler changeHandler`
-> 
`getTransactionIndexer`

And this runs in an infite loop for a `ControllerHostedRouter`

```java
    @Override @NonNull
    Router getRootRouter() {
        if (hostController != null && hostController.getRouter() != null) {
            return hostController.getRouter().getRootRouter();
        } else {
            return this;
        }
    }

    @Override @Nullable
    TransactionIndexer getTransactionIndexer() {
        return getRootRouter().getTransactionIndexer();
    }
```

**Comment by PaulWoitaschek** [comment] 2017-03-10 08:06
The problem is that there is no host controller.

Now that I replaced `push` with `setRoot` conductor throws a NPE because `ControllerHostedRouter#getSiblingRouters` calls `hostController.getChildRouters` and `hostController` is null.

There is something special about the way I setup the router. It's the result of a RxJava Observable and looks like:

```java
stream()
  .observeOn(AndroidSchedulers.mainThread)
  .compose(bindToLifecycle())
  .subscribe( it -> {
    if(!router.hasRootController)  router.setRootController(RouterTransaction...)
  }
```

**Comment by EricKuck** [comment] 2017-03-31 14:44
Do you have a way to reproduce this? I took a quick look through and no possible causes are sticking out.

**Comment by blazeroni** [comment] 2017-04-12 22:28
We're seeing a related error in our crash logs.  We get a StackOverflowError with recursive calls to `getTransactionIndexer`.  One notable thing is that the stack trace always includes a ViewPager.

We have been unable to reproduce this ourselves, though.

**Comment by PaulWoitaschek** [comment] 2017-04-13 18:49
I couldn't reproduce it in my own builds either. In the meantime I refactored that part for different reasons, so @blazeroni might take over reporting when this is fixed.

**Comment by EricKuck** [comment] 2017-05-03 19:43
@blazeroni Would it be possible to post a full stacktrace? I've had no success reproducing this.

**Comment by blazeroni** [comment] 2017-05-16 21:14
I don't have a full stack trace available (we've worked around this issue), but I can tell you that it was triggered by a view layout.  Even though we never reproduced it locally, we could tell from logs that a request to layout the view was somehow getting called before the controllers were re-initialized.  Normally, this is fine except that the ViewPager is handling controllers without a fully initialized parent controllers, causing this issue.

**Comment by EricKuck** [comment] 2017-05-18 15:30
This should finally be fixed by 926f7da6cec399243d3b0bed8b78fe3adc20c92c. It took forever to reproduce, but you shouldn't see this again in the latest snapshot. A new release will come within the next few days.

**Closed by EricKuck** 2017-05-18 15:30 UTC

**Comment by PaulWoitaschek** [comment] 2017-05-18 15:44
Thanks a lot for your ongoing support! 

It's fascinating to see how step by step the internal complexity grows with all these edge case issues.

**Comment by EricKuck** [comment] 2017-05-18 16:00
Yeah, no kidding. There are so many rough edges in the Android lifecycle to smooth over!
