### ISSUE TITLE
Shared Elements Animations

### ISSUE THREAD

**Issue by koderbober** [bluelinelabs/Conductor#231] opened 2017-02-14 10:44 UTC
I'm trying to use shared elements animations for one image element as in demo. But all elements faded and image with transitionName faded too. What's wrong? Can somebody help me?

first layout:
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorPrimary"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/logo"
        android:layout_width="match_parent"
        android:layout_height="120dp"
        android:layout_centerHorizontal="true"
        android:padding="30dp"
        android:src="@drawable/logo_black"
        android:transitionName="@string/transition_tag_title" />

    <android.support.design.widget.TabLayout
        android:id="@+id/tab_layout"
        android:layout_width="match_parent"
        android:layout_height="45dp"
        app:tabMode="scrollable"
        app:tabSelectedTextColor="@color/colorAccent"
        app:tabTextColor="@color/colorAccent">

    </android.support.design.widget.TabLayout>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v4.view.ViewPager
            android:id="@+id/view_pager"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        </android.support.v4.view.ViewPager>

    </FrameLayout>

    </LinearLayout>
second layout:
    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/logo"
        android:layout_width="match_parent"
        android:layout_height="120dp"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="50dp"
        android:padding="30dp"
        android:src="@drawable/logo_black"
        android:transitionName="@string/transition_tag_title" />

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="280dp">

        <ImageView
            android:id="@+id/arrow_down"
            android:layout_width="60dp"
            android:layout_height="60dp"
            android:layout_below="@+id/logo"
            android:layout_centerHorizontal="true"
            android:layout_gravity="center_horizontal"
            android:layout_marginTop="20dp"
            android:src="@drawable/arrow_down" />

    </FrameLayout>

    </FrameLayout>

push controller:

     childRouter.pushController(RouterTransaction.with(searchController)
                .pushChangeHandler(new ArcFadeMoveChangeHandlerCompat())
                .popChangeHandler(new ArcFadeMoveChangeHandlerCompat()));

ArcFadeMoveChangeHandlerCompat and ArcFadeMoveChangeHandler as in demo without changes. However, ArcFadeMoveChangeHandler without Fade animations move logo (shared element) correctly.

**Comment by EricKuck** [comment] 2017-02-15 21:33
This is unfortunately the way transitions work when you're not going from one Activity to the next. If you fade a view out, it's going to completely fade out. Unlike Activity transitions, View transitions don't put shared elements into the overlay, so they just get hidden with the other views. There are lots of clever ways around this, and I'm playing with some ideas about how to make a reusable transition component that uses the overlay like you'd expect it to, but I can't guarantee anything will come out of it.

**Comment by EricKuck** [comment] 2017-02-17 15:33
I just had a bit of a revelation on this. It's probably documented somewhere, but I never found it - make sure the views you want to animate all have ids. I just got some really nice transitions working in the demo app simply by adding ids to all the views.

**Comment by nomisRev** [comment] 2017-02-17 16:30
@EricKuck care to elaborate?

**Comment by EricKuck** [comment] 2017-02-17 16:41
I'm working on some more shared element demos to show how this works. You can check out what I have so far here: https://github.com/bluelinelabs/Conductor/tree/feature/shared_element_demos

It looks like simply adding an id to the root of each layout is enough to make the fade out/move shared elements/fade in animations all work as you'd expect them to, but I'm still experimenting with things quite a bit.

**Comment by nomisRev** [comment] 2017-02-17 17:49
@EricKuck if you want me to look into something let me know. I'm playing around with a lot of animations and transitions in a hobby project as well.

**Comment by EricKuck** [comment] 2017-02-20 23:00
I'm not really sure what other kinda shared element transition scenarios there are to demo, really. If there are more I haven't covered, by all means please either let me know or do a PR with a demo!

**Comment by EricKuck** [comment] 2017-03-01 22:50
I _think_ sufficient examples of this are now provided in the demo app, so I'll close this. If more needs come up, please post issues! This stuff is fun to play with.

**Closed by EricKuck** 2017-03-01 22:50 UTC

**Comment by The0ldM0nk** [comment] 2017-05-15 08:45
I think we might have an issue when we mix Conductor, shared element transitions with Android Databinding.
Here is my [fork](https://github.com/The0ldM0nk/Conductor/tree/integration-android-databinding) demonstrating it and the [issue](https://github.com/The0ldM0nk/Conductor/tree/integration-android-databinding).

Would appreciate if you guys can reproduce the issue/elaborate it a bit.
