### ISSUE TITLE
Crash when using ControllerPagerAdapter

### ISSUE THREAD

**Issue by mDroidd** [bluelinelabs/Conductor#198] opened 2017-01-14 17:19 UTC
Hi everyone,

I'm having some trouble with the ControllerPagerAdapter. **My setup is as follows:**
- Router on a FrameLayout.
- Controller with ViewPager is pushed.
- ControllerPagerAdapter is set to the ViewPager. A recyclerview is the only view that's displayed in the page controllers.

**Steps to reproduce the issue:**
- Select "Don't keep activities" or simply run the app on the background of a cheap phone.
- Re-open app, and scroll more pages than the ViewPager keeps in memory (viewPager.setOffscreenPageLimit(int)).

**Stacktrace:**
> Fatal Exception: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.v7.widget.RecyclerView$SavedState
>        at android.os.Parcel.readParcelableCreator(Parcel.java:2432)
>        at android.os.Parcel.readParcelable(Parcel.java:2358)
>        at android.os.Parcel.readValue(Parcel.java:2264)
>        at android.os.Parcel.readSparseArrayInternal(Parcel.java:2675)
>        at android.os.Parcel.readSparseArray(Parcel.java:1967)
>        at android.os.Parcel.readValue(Parcel.java:2321)
>        at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
>        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
>        at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
>        at com.bluelinelabs.conductor.Controller.restoreViewState(Controller.java:1002)
>        at com.bluelinelabs.conductor.Controller.inflate(Controller.java:894)
>        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:159)
>        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:652)
>        at com.bluelinelabs.conductor.Router.rebindIfNeeded(Router.java:435)
>        at com.bluelinelabs.conductor.support.ControllerPagerAdapter.instantiateItem(ControllerPagerAdapter.java:61)
>        at com.mappz.zerotohero.ui.controllers.workout.WorkoutDisplayAdapter.instantiateItem(WorkoutDisplayAdapter.java:56)
>        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
>        at android.support.v4.view.ViewPager.populate(ViewPager.java:1248)
>        at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
>        at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
>        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
>        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
>        at android.view.Choreographer.doFrame(Choreographer.java:603)
>        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
>        at android.os.Handler.handleCallback(Handler.java:739)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:152)
>        at android.app.ActivityThread.main(ActivityThread.java:5507)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Possibly related to [https://code.google.com/p/android/issues/detail?id=196430](https://code.google.com/p/android/issues/detail?id=196430), but it's stated there that this issue should be fixed in support library 24.0.0. I'm running 25.1.0, which is why I'm reporting it here.

Please excuse me if this is a duplicate issue or unrelated to Conductor. Happy to get all the help I can get on this one.

**Comment by EricKuck** [comment] 2017-01-15 22:48
I've never seen this one and don't _think_ it's related to Conductor, as it appears to be directly caused by the support library. Checking the issue link you sent, it looks as if several people are saying this still happens on 25.1.0. Which version of Android are you seeing this crash on?

**Comment by mDroidd** [comment] 2017-01-15 22:56
I'm running Android 7.0 at the moment. At this moment, one person commented this still happens on 25.1.0 in that google thread and that person is me, although that thread also contains 1 report for that particular crash on 25.0.1.

I was wondering if a catch around getSparseParcelableArray(at Controller.java:1002) would be acceptable as a fix for this crash, or you'd rather have me fork a branch and do so myself.

That would ofcourse just be a temporary workaround until the support library fixes the issue.

**Comment by EricKuck** [comment] 2017-01-15 23:23
I don't think I'd want to catch an Exception that happens here, as it would leave apps in an undefined state. If you want to temporarily add this on a private fork until they've fixed the support library that might work for you though. 

If I understand the issue correctly, it seems like the Bundle may have a null ClassLoader. I can't reproduce this error and am going into this a little blind, but can you try this on a fork of this lib to see if this fixes it for you? At `Controller:1002`, add this line: `viewState.setClassLoader(getActivity().getClass().getClassLoader())`. If that works I'll add it to the lib and we should be good to go.

**Comment by PaulWoitaschek** [comment] 2017-01-16 05:44
One of the +1 guys is actually me using conductor. Just as a note even though I don't believe this is conductors fault.

**Comment by mDroidd** [comment] 2017-01-16 07:43
I'll see what I can do on the private branch. Might take a while as I'm not used to doing this.

Thanks for the support so far.

**Comment by EricKuck** [comment] 2017-01-18 18:18
I just committed a potential fix to the develop branch. Can you try with the latest snapshot and let me know if that works?

**Comment by mDroidd** [comment] 2017-01-18 18:42
Holy moly it worked! I must it was unexpected, as I found 4 or 5 related bugreports on googlecode, but this solved it. Thanks for the great library and great support!

**Comment by EricKuck** [comment] 2017-01-18 18:48
Awesome, thanks for letting me know it works!

**Closed by EricKuck** 2017-01-18 18:48 UTC

**Comment by PaulWoitaschek** [comment] 2017-01-19 05:53
So you understand why this is necessary? And why it crashes with fragments too?
And what the whole class loader is meant for in the bundle?
