### ISSUE TITLE
Setting Controller to Retained calls its attach method twice

### ISSUE THREAD

**Issue by prashermanas** [bluelinelabs/Conductor#129] opened 2016-10-04 22:43 UTC
It seems weird but whenever i try to make the Controller method twice and i switch the retained controller to some other controller , the retained controller attach is called again.

It doesn't happen if the controller is not retained

**Comment by EricKuck** [comment] 2016-10-05 20:29
I'm not really clear on what the issue you're facing is. I did what I thought you meant, but it worked fine. Can you explain a little more?

**Comment by prashermanas** [comment] 2016-10-06 15:21
Ok, So AFAIK the controller attached method should be called when the controller is in focus and detached method is called when not in focus.

So here is what i did :

I made the controller 'A' retained.
Now when the controller 'A' is in focus onAttach method is called (this is fine).
But when i open another controller 'B' controller 'A's onattach method is called again (which shouldn't happen as the controller 'A' is not in focus.

So what i am thinking is there is bug in the lifecycle of retained controller as its attach method is called twice once when the controller is in focus and the other when the controller goes out of focus

**Comment by EricKuck** [comment] 2016-10-06 15:46
So the `onAttach` method doesn't mean focused, it means that it is attached to the window. In the case of two controllers both being attached to the window at the same time, they would both be in the attached state, even if one's view is completely obstructed by another's.

I still can't reproduce `onAttach` being called twice though. When you say a controller is retained, I assume you mean that you've set the `retainViewMode` to `RETAIN_DETACH`? And when you say you're opening another controller, I assume you mean you're pushing another one to the router?

Also, which `ControllerChangeHandler` are you using?

**Comment by prashermanas** [comment] 2016-10-06 17:05
yeah by opening controller i mean pushing another controller to the router and when i say retained controller i set the retainViewMode RETAIN_DETACH.
I am using AutoTransitionChangeHandler.

**Comment by EricKuck** [comment] 2016-10-06 19:44
Ah, the issue here is the `AutoTransitionChangeHandler`. As noted in #113, Android actually detaches, then reattaches your view in order to calculate how the transition will happen. So getting the callback twice in this case is technically not wrong, but it's definitely not expected. I'd like to fix this, but I haven't found a way to detect that a view is being detached/reattached due to a transition vs. legitimately being detached and reattached.

I'm closing this for now, as it's actually a dupe of #113, but if you find anything of interest, please let me know.

**Closed by EricKuck** 2016-10-06 19:44 UTC
